#!/usr/bin/env python3
"""
Generates data/words.js — the 5-letter word database for the Wordle clone.

Not loaded by the running app; this is a one-time (or re-runnable) content
generation script.

Source: words.txt at the repo root — the Stanford GraphBase 5-letter word
list (5,757 words), ordered from most to least frequent in English usage.
This is a well-established, publicly available word-frequency list (Donald
Knuth's Stanford GraphBase project), used as-is with no network calls.

Method:
1. Read words.txt, one word per line, already ordered by frequency
   (most common first).
2. Drop a short blocklist of slurs/vulgar terms present in the raw list.
3. Take the top 70% (most frequent) as the COMMON tier and the bottom 30%
   (least frequent) as the HARD tier — matching the frequency ordering
   already in the source file.
4. Uppercase, shuffle (fixed seed, for reproducibility), and emit
   data/words.js as a flat array.
"""
import random

SOURCE_PATH = "words.txt"

# Slurs / vulgar terms present in the raw Stanford GraphBase list — excluded
# for a public, general-audience game.
BLOCKLIST = {
    "squaw", "pussy", "bitch", "penis", "raped", "dykes", "chink", "rapes",
    "homos", "raper", "whore", "sluts", "fucks", "kikes", "cunts", "feces",
    "dildo", "spics", "turds", "twats", "gooks", "coons",
}

def main():
    with open(SOURCE_PATH) as f:
        words = [w.strip().lower() for w in f if w.strip()]

    words = [w for w in words if w not in BLOCKLIST]

    total = len(words)
    common_count = round(total * 0.70)
    common_tier = words[:common_count]
    hard_tier = words[common_count:]

    print(f"Total words (post-blocklist): {total}")
    print(f"Common tier: {len(common_tier)} ({len(common_tier)/total:.0%})")
    print(f"Hard tier: {len(hard_tier)} ({len(hard_tier)/total:.0%})")

    all_words = [w.upper() for w in (common_tier + hard_tier)]
    rng = random.Random(42)
    rng.shuffle(all_words)

    with open("data/words.js", "w") as f:
        f.write("// Auto-generated by tools/generate_words.py — see that file for methodology.\n")
        f.write(f"// {len(all_words)} words: {len(common_tier)} common-tier + {len(hard_tier)} hard-tier,\n")
        f.write("// sourced from the Stanford GraphBase 5-letter word list (words.txt).\n")
        f.write("export const WORDS = [\n")
        line = "  "
        for w in all_words:
            token = f'"{w}",'
            if len(line) + len(token) > 100:
                f.write(line.rstrip() + "\n")
                line = "  "
            line += token + " "
        if line.strip():
            f.write(line.rstrip() + "\n")
        f.write("];\n")

if __name__ == "__main__":
    main()
